server:
  port: 8080

mybatis.config: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #数据库连接池配置
    max-active: 50
    max-idle: 20
    min-idle: 10
    initial-size: 10
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 60000
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)

flyway.baselineOnMigrate: true